- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Enable Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Ensure docker cli-plugins directory exists
  file:
    path: /usr/local/lib/docker/cli-plugins
    state: directory
    mode: "0755"

- name: Install Docker Compose v2 plugin
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.25.0/docker-compose-linux-x86_64
    dest: /usr/local/lib/docker/cli-plugins/docker-compose
    mode: "0755"
