clickhouse_container_name: clickhouse
clickhouse_image: clickhouse/clickhouse-server:latest
clickhouse_ports:
  - "8123:8123"
  - "9000:9000"

clickhouse_data_dir: /opt/clickhouse/data
clickhouse_config_dir: /opt/clickhouse/config
clickhouse_compose_dir: /opt/clickhouse
clickhouse_restart_policy: unless-stopped
