minio_version: "RELEASE.2024-01-16T16-07-38Z"

minio_root_user: minioadmin
minio_root_password: minioadmin123

minio_data_dir: /data/minio
minio_compose_dir: /opt/minio

minio_api_port: 9000
minio_console_port: 9001
