- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Enable Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Install Docker Compose v2 plugin
  apt:
    name: docker-compose-plugin
    state: present
