- name: Create prometheus user
  user:
    name: prometheus
    shell: /usr/sbin/nologin
    system: yes

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz

- name: Extract prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy binaries
  copy:
    src: "/tmp/prometheus-2.49.1.linux-amd64/{{ item }}"
    dest: /usr/local/bin/{{ item }}
    owner: prometheus
    group: prometheus
    mode: '0755'
    remote_src: yes
  loop:
    - prometheus
    - promtool

- name: Copy prometheus config
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus

- name: Create systemd service
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target

      [Service]
      User={{ prometheus_user }}
      Group={{ prometheus_user }}
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
        --config.file={{ prometheus_config_path }} \
        --storage.tsdb.path={{ prometheus_data_path }} \
        --web.listen-address=:{{ prometheus_port }}

      Restart=always
      RestartSec=5

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd
  command: systemctl daemon-reexec

- name: Enable & start prometheus
  systemd:
    name: prometheus
    enabled: yes
    state: started
