tigerbeetle_port: 3010


yugabyte_version: "2.20.1.0"
yugabyte_data_dir: /data/yugabyte


scylla_image: "scylladb/scylla:5.4"
scylla_memory: "2G"
scylla_smp: 2
scylla_ports:
  - "9042:9042"
  - "9160:9160"


aerospike_version: "7.0.0"
aerospike_user: aerospike
aerospike_group: aerospike
aerospike_service_port: 3000
aerospike_fabric_port: 3001
aerospike_heartbeat_port: 3002
aerospike_data_dir: /opt/aerospike/data
aerospike_log_dir: /var/log/aerospike
aerospike_namespace: test
aerospike_memory_size: 1G
aerospike_storage_file_size: 2G
aerospike_cluster_name: infra-cluster
aerospike_bind_address: "0.0.0.0"


