tigerbeetle_port: 3010


yugabyte_version: "2.20.1.0"
yugabyte_data_dir: /data/yugabyte


scylla_image: "scylladb/scylla:5.4"
scylla_memory: "2G"
scylla_smp: 2
scylla_ports:
  - "9042:9042"
  - "9160:9160"


aerospike_container_name: "aerospike"
aerospike_image: "aerospike/aerospike-server:7.0.0.0"
aerospike_base_dir: "/opt/aerospike"
aerospike_data_dir: "/opt/aerospike/data"
aerospike_log_dir: "/opt/aerospike/logs"
aerospike_service_port: 3000
aerospike_heartbeat_port: 3002
aerospike_fabric_port: 3001
aerospike_info_port: 3003
aerospike_ports:
  - "3000:3000"
  - "3001:3001"
  - "3002:3002"
  - "3003:3003"




