# tempo
tempo_image: grafana/tempo:latest
tempo_http_port: 3200
tempo_grpc_port: 4317

# mimir
mimir_image: grafana/mimir:latest
mimir_http_port: 9600

# loki
loki_image: grafana/loki:2.9.4
loki_http_port: 3100
